In [ ]:
import pandas as pd
# Fix the bridge between new Pandas and old Datareader
pd.core.common.is_list_like = pd.api.types.is_list_like

import pandas_datareader.data as pdr

brent = pdr.get_data_fred("DCOILBRENTEU", start="2023-01-01")
brent = brent.resample("MS").mean()

TypeError: deprecate_kwarg() missing 1 required positional argument: 'new_arg_name'

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/home/moritus-peters/Documents/UNI_LAG_PROJECT/USD_NGN Historical Data.csv")
df

           Date      Price       Open       High        Low  Vol. Change %
0    01/04/2026  1,375.735  1,385.540  1,388.520  1,337.500   NaN   -0.77%
1    01/03/2026  1,386.460  1,359.500  1,418.920  1,347.870   NaN    1.80%
2    01/02/2026  1,361.880  1,392.000  1,401.830  1,333.795   NaN   -1.77%
3    01/01/2026  1,386.455  1,444.575  1,448.750  1,375.645   NaN   -4.02%
4    01/12/2025  1,444.570  1,443.000  1,464.645  1,439.745   NaN   -0.19%
..          ...        ...        ...        ...        ...   ...      ...
226  01/06/2007    127.250    127.250    127.250    127.250   NaN   -0.31%
227  01/05/2007    127.650    127.650    127.650    127.650   NaN    0.16%
228  01/04/2007    127.450    127.450    127.450    127.450   NaN   -0.39%
229  01/03/2007    127.950    127.950    127.950    127.950   NaN   -0.23%
230  01/02/2007    128.250    128.250    128.250    128.250   NaN    0.04%

[231 rows x 7 columns]

In [9]:
df1 = pd.read_csv("/home/moritus-peters/Documents/UNI_LAG_PROJECT/DCOILBRENTEU.csv")
df1

     observation_date  DCOILBRENTEU
0          2007-01-31         56.52
1          2007-02-01         56.74
2          2007-02-02         56.93
3          2007-02-05         58.67
4          2007-02-06         58.04
...               ...           ...
5017       2026-04-24        111.86
5018       2026-04-27        113.89
5019       2026-04-28        117.62
5020       2026-04-29        124.16
5021       2026-04-30        124.24

[5022 rows x 2 columns]